service: wipeLogService

package:
  individually: true

provider:
  name: aws
  runtime: ruby2.5
  stage: production
  region: ap-southeast-1
  endpointType: REGIONAL

functions:
  wipe_log:
    handler: handler.wipe_log
    events:
      - http: DELETE wipe_log
    package:
      exclude:
        - README.md
        - Rakefile
        - tasks/**
        - Dockerfile
        - docker-compose.yml
        - .bundle
        - Gemfile*
        - package*
        - node_modules/**
        - .dockerignore

plugins:
  - serverless-offline

custom:
  serverless-offline:
    host: '0.0.0.0'
    port: 3000
